devices:
  IP2CC:
    - id: 0
      name: "IP2CC Device Identifier"
      host: 192.168.1.70 # Default IP for no DHCP
      contact_closure:
        port1: 
          - name: "Device One" # What will be displayed on UI for control panel
            pwr_on_state : 0   # After power loss what should be the port state (default: 0)
        port2: 
          - name: "Device Two"
            pwr_on_state: 0
        port3: 
          - name: "Device Three"
            pwr_on_state : 0

settings:
  web_api_server_port: 8000

database:
  path: itach.db

logging:
  path: itach.log
